//! Middle tier of the context pyramid.
//!
//! Daily / weekly / monthly / quarterly summaries — generated by an LLM call
//! on demand. v0.5 auto-generates DAY summaries at session-end (yesterday's
//! window if missing). Higher tiers are manually triggered via
//! `folkbot summaries roll-up <period>`.
//!
//! Time math is in Asia/Hong_Kong (UTC+8) for v0.5 — TODO: detect/configure.

use anyhow::{bail, Context, Result};
use futures_util::StreamExt;
use serde::{Deserialize, Serialize};
use sqlx::SqlitePool;

use crate::storage::db::now_ts;
use crate::llm::{LlmProvider, Message, StreamChunk};

const DAY_SECS: i64 = 86400;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Period {
    Day,
    Week,
    Month,
    Quarter,
}

impl Period {
    pub fn parse(s: &str) -> Option<Self> {
        Some(match s.to_ascii_lowercase().as_str() {
            "day" | "daily" | "d" => Self::Day,
            "week" | "weekly" | "w" => Self::Week,
            "month" | "monthly" | "mo" | "m" => Self::Month,
            "quarter" | "quarterly" | "q" => Self::Quarter,
            _ => return None,
        })
    }
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Day => "day",
            Self::Week => "week",
            Self::Month => "month",
            Self::Quarter => "quarter",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Summary {
    pub id: i64,
    pub user_id: i64,
    pub period: Period,
    pub start_ts: i64,
    pub end_ts: i64,
    pub content: String,
    /// Reserved for `summaries list` to show "generated when".
    #[allow(dead_code)]
    pub created_at: i64,
}

#[derive(sqlx::FromRow)]
struct SummaryRow {
    id: i64,
    user_id: i64,
    period: String,
    start_ts: i64,
    end_ts: i64,
    content: String,
    created_at: i64,
}

impl SummaryRow {
    fn into_summary(self) -> Summary {
        Summary {
            id: self.id,
            user_id: self.user_id,
            period: Period::parse(&self.period).unwrap_or(Period::Day),
            start_ts: self.start_ts,
            end_ts: self.end_ts,
            content: self.content,
            created_at: self.created_at,
        }
    }
}

pub async fn list_recent(
    pool: &SqlitePool,
    user_id: i64,
    period: Period,
    limit: usize,
) -> Result<Vec<Summary>> {
    let rows: Vec<SummaryRow> = sqlx::query_as(
        "SELECT id, user_id, period, start_ts, end_ts, content, created_at FROM summaries
         WHERE user_id = ? AND period = ?
         ORDER BY end_ts DESC LIMIT ?",
    )
    .bind(user_id)
    .bind(period.as_str())
    .bind(limit as i64)
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(|r| r.into_summary()).collect())
}

/// Local-day boundary: the unix-ts at local-midnight that `ts` falls into.
/// "Local" = the offset configured via `[agent] timezone_offset_secs`.
pub(crate) fn local_day_floor(ts: i64) -> i64 {
    let off = crate::util::tz_offset();
    let local = ts + off;
    let day_local = (local / DAY_SECS) * DAY_SECS;
    day_local - off
}

/// Return (start, end) in unix-ts for "yesterday" relative to `now`.
pub(crate) fn yesterday_window(now: i64) -> (i64, i64) {
    let today = local_day_floor(now);
    (today - DAY_SECS, today)
}

/// If yesterday has messages but no summary, summarize and persist. Returns
/// `Ok(true)` if a new summary was written.
pub async fn ensure_yesterday_daily(
    pool: &SqlitePool,
    llm: &dyn LlmProvider,
    user_id: i64,
    user_name: &str,
) -> Result<bool> {
    let (start, end) = yesterday_window(now_ts());

    // Already done?
    let existing: Option<(i64,)> = sqlx::query_as(
        "SELECT id FROM summaries
         WHERE user_id = ? AND period = 'day' AND start_ts = ? AND end_ts = ?",
    )
    .bind(user_id)
    .bind(start)
    .bind(end)
    .fetch_optional(pool)
    .await?;
    if existing.is_some() {
        return Ok(false);
    }

    // Pull yesterday's messages.
    let msgs: Vec<(String, String)> = sqlx::query_as(
        "SELECT role, content FROM messages
         WHERE user_id = ? AND ts >= ? AND ts < ? AND role IN ('user','assistant')
         ORDER BY ts ASC, id ASC",
    )
    .bind(user_id)
    .bind(start)
    .bind(end)
    .fetch_all(pool)
    .await?;
    if msgs.is_empty() {
        return Ok(false);
    }

    let summary = run_summary(
        llm,
        user_name,
        &msgs,
        "Condense the following yesterday's conversation into a third-person diary-style summary of ≤300 chars, \
         focusing on topics, events, decisions, mood. **Do not quote verbatim.** Output plain text, no markdown headers, no prefix.",
    )
    .await?;

    if summary.trim().is_empty() {
        return Ok(false);
    }

    sqlx::query(
        "INSERT OR IGNORE INTO summaries (user_id, period, start_ts, end_ts, content, created_at)
         VALUES (?, 'day', ?, ?, ?, ?)",
    )
    .bind(user_id)
    .bind(start)
    .bind(end)
    .bind(summary.trim())
    .bind(now_ts())
    .execute(pool)
    .await?;
    Ok(true)
}

/// Roll up a higher-tier summary from lower-tier ones.
///
/// **Cascade-aware**: if a previous target summary exists, only consider
/// source summaries with `end_ts > previous_target.end_ts` (in chronological
/// order, oldest first). This way running roll-up repeatedly only writes a
/// new entry when there's enough fresh material.
///
/// Maps:
///   week    ← 7 day summaries
///   month   ← 4 week summaries
///   quarter ← 3 month summaries
pub async fn roll_up(
    pool: &SqlitePool,
    llm: &dyn LlmProvider,
    user_id: i64,
    user_name: &str,
    target: Period,
) -> Result<bool> {
    let (source, count) = match target {
        Period::Week => (Period::Day, 7usize),
        Period::Month => (Period::Week, 4),
        Period::Quarter => (Period::Month, 3),
        Period::Day => bail!("can't roll up *to* day; ensure_yesterday_daily handles it"),
    };

    let last_target_end: i64 = sqlx::query_scalar(
        "SELECT COALESCE(MAX(end_ts), 0) FROM summaries WHERE user_id = ? AND period = ?",
    )
    .bind(user_id)
    .bind(target.as_str())
    .fetch_one(pool)
    .await?;

    // Pull source summaries that haven't been rolled up yet, oldest first.
    let pending_rows: Vec<SummaryRow> = sqlx::query_as(
        "SELECT id, user_id, period, start_ts, end_ts, content, created_at FROM summaries
         WHERE user_id = ? AND period = ? AND end_ts > ?
         ORDER BY end_ts ASC LIMIT ?",
    )
    .bind(user_id)
    .bind(source.as_str())
    .bind(last_target_end)
    .bind(count as i64)
    .fetch_all(pool)
    .await?;
    let pending: Vec<Summary> = pending_rows.into_iter().map(|r| r.into_summary()).collect();
    if pending.len() < count {
        bail!(
            "need {} fresh {} summaries to roll up to {} (have {} unrolled-up)",
            count,
            source.as_str(),
            target.as_str(),
            pending.len()
        );
    }

    let start = pending.first().map(|s| s.start_ts).unwrap();
    let end = pending.last().map(|s| s.end_ts).unwrap();

    // Already exists for this exact window?
    let existing: Option<(i64,)> = sqlx::query_as(
        "SELECT id FROM summaries
         WHERE user_id = ? AND period = ? AND start_ts = ? AND end_ts = ?",
    )
    .bind(user_id)
    .bind(target.as_str())
    .bind(start)
    .bind(end)
    .fetch_optional(pool)
    .await?;
    if existing.is_some() {
        return Ok(false);
    }

    let mut transcript = String::new();
    for s in &pending {
        transcript.push_str(&format!(
            "--- {} (ts={}~{}) ---\n{}\n\n",
            source.as_str(),
            s.start_ts,
            s.end_ts,
            s.content
        ));
    }

    let prompt = match target {
        Period::Week => "Condense the following 7 daily summaries into this week's recap, ≤400 chars, third person, focusing on main threads, progress, turning points.",
        Period::Month => "Condense the following 4 weekly recaps into this month's overall context, ≤500 chars, focusing on long-term themes and changes.",
        Period::Quarter => "Condense the following 3 monthly recaps into this quarter's overall outline, ≤600 chars, describing the big-picture direction across this period.",
        Period::Day => unreachable!(),
    };

    let wire = vec![Message::system(prompt), Message::user(transcript)];
    let mut stream = llm.stream(wire, vec![]).await.context("roll-up LLM call")?;
    let mut content = String::new();
    while let Some(chunk) = stream.next().await {
        if let Ok(StreamChunk::Text(t)) = chunk {
            content.push_str(&t);
        }
    }
    let content = content.trim();
    if content.is_empty() {
        bail!("roll-up returned empty content");
    }

    sqlx::query(
        "INSERT OR IGNORE INTO summaries (user_id, period, start_ts, end_ts, content, created_at)
         VALUES (?, ?, ?, ?, ?, ?)",
    )
    .bind(user_id)
    .bind(target.as_str())
    .bind(start)
    .bind(end)
    .bind(content)
    .bind(now_ts())
    .execute(pool)
    .await?;
    let _ = user_name;
    Ok(true)
}

/// Try to roll up week, month, quarter in order. Each successful roll-up
/// might enable the next tier. Stops at the first one that can't roll up
/// (not enough source material).
///
/// Returns the list of periods that were just written.
pub async fn cascade_rollup(
    pool: &SqlitePool,
    llm: &dyn LlmProvider,
    user_id: i64,
    user_name: &str,
) -> Result<Vec<Period>> {
    let mut rolled = Vec::new();
    for target in [Period::Week, Period::Month, Period::Quarter] {
        match roll_up(pool, llm, user_id, user_name, target).await {
            Ok(true) => rolled.push(target),
            Ok(false) => {} // already exists; continue to next tier
            Err(_) => break, // not enough source — and higher tiers won't have enough either
        }
    }
    Ok(rolled)
}

async fn run_summary(
    llm: &dyn LlmProvider,
    user_name: &str,
    msgs: &[(String, String)],
    instruction: &str,
) -> Result<String> {
    let mut transcript = String::new();
    for (role, content) in msgs {
        let speaker = if role == "user" { user_name } else { "Folkbot" };
        transcript.push_str(&format!("{}: {}\n", speaker, content));
    }
    let wire = vec![Message::system(instruction), Message::user(transcript)];
    let mut stream = llm.stream(wire, vec![]).await?;
    let mut out = String::new();
    while let Some(chunk) = stream.next().await {
        if let Ok(StreamChunk::Text(t)) = chunk {
            out.push_str(&t);
        }
    }
    Ok(out)
}

/// Refresh `users.last_summary` for one user — the rolling "vibe" used by
/// other users' system prompts to know what this person's been up to.
///
/// This used to live in `main.rs::summarize_session` and only fired on
/// CLI Ctrl+D. Moved here so the background compressor can also run it
/// for Telegram-only users (who have no Ctrl+D event).
pub async fn refresh_user_vibe(
    pool: &SqlitePool,
    llm: &dyn LlmProvider,
    user_id: i64,
    user_name: &str,
) -> Result<bool> {
    // v1.2: span all conversations the user has spoken in (DM + rooms),
    // not just DM. Each line tagged with conv label so the summary can
    // distinguish "in the family group discussing with Lucky..." vs "in DM telling me...".
    let recent = crate::storage::messages::load_last_n_for_user_all_convs(pool, user_id, 30).await?;
    if recent.is_empty() {
        return Ok(false);
    }
    // Cache conv labels to avoid repeated lookups.
    let mut conv_label: std::collections::HashMap<i64, String> =
        std::collections::HashMap::new();
    for (_, _, cid) in &recent {
        if conv_label.contains_key(cid) {
            continue;
        }
        // v1.2.1: DM sentinel is 0, not 1 (rooms get auto-incremented ids ≥1).
        let tag = if *cid == 0 {
            "DM".to_string()
        } else {
            match crate::storage::conversations::label(pool, *cid).await? {
                Some(l) => format!("group \"{}\"", l),
                None => format!("group#{}", cid),
            }
        };
        conv_label.insert(*cid, tag);
    }
    let mut transcript = String::new();
    for (m, ts, cid) in &recent {
        let speaker = match m.role {
            crate::llm::Role::User => user_name,
            crate::llm::Role::Assistant => "Folkbot",
            _ => continue,
        };
        if let Some(c) = &m.content {
            let where_ = conv_label.get(cid).map(|s| s.as_str()).unwrap_or("?");
            transcript.push_str(&format!(
                "[{} | {}] {}: {}\n",
                crate::util::fmt_ts(*ts),
                where_,
                speaker,
                c.as_text()
            ));
        }
    }
    let wire = vec![
        Message::system(
            "You are a conversation summarizer. Condense the following conversation into a ≤250-char third-person narrative, \
             focusing on topics, decisions, emotions. The `[time | place]` at the start of each line shows where it happened \
             (DM = private message, group \"X\" = that group). The summary can mention \"in DM\" or \"in group X\" \
             to distinguish settings. **Do not quote any message verbatim.** \
             Output plain text, no prefix, no markdown headers.",
        ),
        Message::user(transcript),
    ];
    let mut stream = llm.stream(wire, vec![]).await?;
    let mut summary = String::new();
    while let Some(chunk) = stream.next().await {
        if let Ok(StreamChunk::Text(t)) = chunk {
            summary.push_str(&t);
        }
    }
    let summary = summary.trim();
    if summary.is_empty() {
        return Ok(false);
    }
    crate::storage::users::save_summary(pool, user_id, summary).await?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    // 2026-04-30 12:00 in HK (+8h) — known wall-clock for predictable boundary math.
    // 2026-04-30 04:00 UTC = 1777953600 (= 1777939200 day-floor + 4h).
    const TS_HK_NOON: i64 = 1777953600;

    #[test]
    fn local_day_floor_lands_on_hk_midnight() {
        // HK midnight on 2026-04-30 is 2026-04-29 16:00 UTC = TS_HK_NOON - 12h.
        let floor = local_day_floor(TS_HK_NOON);
        assert_eq!(floor, TS_HK_NOON - 12 * 3600);
    }

    #[test]
    fn yesterday_window_is_24h_wide_and_ends_at_today_floor() {
        let (start, end) = yesterday_window(TS_HK_NOON);
        assert_eq!(end - start, DAY_SECS);
        assert_eq!(end, local_day_floor(TS_HK_NOON));
    }
}
